# Site settings
title: Educloud Alliance
email: jussi.hurmola@educloudalliance.org
url: http://educloudalliance.org
baseurl:
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: '#fff'
  primary-fg: '#333'
  links: '#219ab3'

# Footer settings
footer: Educloud Alliance

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/educloudallianc
  - title: facebook
    url: https://facebook.com/educloudalliance
  - title: github
    url: https://github.com/educloudalliance

# Build settings
markdown: kramdown
permalink: pretty

